ALTER TABLE `t_application`
ADD COLUMN `main_pic`  varchar(500) NULL COMMENT '主图片' AFTER `update_time`;

-- ----------------------------
-- View structure for `v_application_cn`
-- ----------------------------
DROP VIEW IF EXISTS `v_application_cn`;
CREATE ALGORITHM=UNDEFINED DEFINER=`carit`@`%` SQL SECURITY DEFINER VIEW `v_application_cn` AS select `a`.`id` AS `id`,`a`.`app_name` AS `app_name`,`a`.`icon` AS `icon`,`a`.`big_icon` AS `big_icon`,`g`.`name` AS `developer`,`g`.`website` AS `website`,`g`.`email` AS `email`,`a`.`version` AS `version`,`b`.`name` AS `catalog_name`,`a`.`catalog_id` AS `catalog_id`,`a`.`size` AS `size`,`a`.`app_file_path` AS `app_file_path`,`f`.`display_value` AS `platform`,`h`.`display_value` AS `support_languages`,`a`.`price` AS `price`,`a`.`down_count` AS `down_count`,`a`.`app_level` AS `app_level`,`a`.`description` AS `description`,`a`.`permission_desc` AS `permission_desc`,`a`.`features` AS `features`,`a`.`images` AS `images`,`a`.`update_time` AS `update_time`,`a`.`status` AS `status`,`a`.`main_pic` AS `main_pic` from ((((`t_application` `a` left join `t_app_catalog` `b` on((`a`.`catalog_id` = `b`.`id`))) left join `t_base_field` `f` on((`a`.`platform` = `f`.`field_value`))) left join `t_base_field` `h` on((`a`.`support_languages` = `h`.`field_value`))) left join `t_app_developer` `g` on((`a`.`developer` = `g`.`id`))) where ((`a`.`status` > 0) and (`f`.`field` = 'platform') and (`h`.`field` = 'suppor_language')) ;

-- ----------------------------
-- View structure for `v_application_en`
-- ----------------------------
DROP VIEW IF EXISTS `v_application_en`;
CREATE ALGORITHM=UNDEFINED DEFINER=`carit`@`%` SQL SECURITY DEFINER VIEW `v_application_en` AS select `a`.`id` AS `id`,`a`.`en_name` AS `app_name`,`a`.`icon` AS `icon`,`a`.`big_icon` AS `big_icon`,`g`.`name` AS `developer`,`g`.`website` AS `website`,`g`.`email` AS `email`,`a`.`version` AS `version`,`b`.`en_name` AS `catalog_name`,`a`.`catalog_id` AS `catalog_id`,`a`.`size` AS `size`,`a`.`app_file_path` AS `app_file_path`,`f`.`display_value` AS `platform`,`h`.`display_value` AS `support_languages`,`a`.`price` AS `price`,`a`.`down_count` AS `down_count`,`a`.`app_level` AS `app_level`,`a`.`en_description` AS `description`,`a`.`en_permission_desc` AS `permission_desc`,`a`.`en_features` AS `features`,`a`.`images` AS `images`,`a`.`update_time` AS `update_time`,`a`.`status` AS `status`,`a`.`main_pic` AS `main_pic` from ((((`t_application` `a` left join `t_app_catalog` `b` on((`a`.`catalog_id` = `b`.`id`))) left join `t_base_field` `f` on((`a`.`platform` = `f`.`field_value`))) left join `t_base_field` `h` on((`a`.`support_languages` = `h`.`field_value`))) left join `t_app_developer` `g` on((`a`.`developer` = `g`.`id`))) where ((`a`.`status` > 0) and (`f`.`field` = 'platform') and (`h`.`field` = 'suppor_language')) ;